# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-30 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_title', models.CharField(max_length=200)),
                ('item_description', models.CharField(max_length=200)),
                ('item_seller', models.CharField(max_length=200)),
                ('item_menhaj', models.CharField(max_length=200)),
                ('item_price', models.IntegerField(default=0)),
                ('item_off', models.IntegerField(default=0)),
            ],
        ),
    ]
