# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-30 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_items_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersEmails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=200)),
            ],
        ),
    ]
