# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-01 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_usersemails'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='item_image',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
