# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-01 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_items_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='item_short_description',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
